gestor_controllers:
    resource: '../src/Controller/Gestor/'
    type: attribute
    prefix: /gestor

participante_controllers:
    resource: '../src/Controller/Participante/'
    type: attribute
    prefix: /participante

formador_controllers:
    resource: '../src/Controller/Formador/'
    type: attribute
    prefix: /formador
