name: Run PHPStan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Ajusta según tu versión de PHP
        extensions: mbstring, dom, pdo, xml

    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --no-interaction --dev

    - name: List vendor/bin directory
      run: ls -al vendor/bin
    
    - name: Run PHPStan
      run: vendor/bin/phpstan analyse

