name: Symfony Tests

on:
  push:
    branches:
      - developer
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: bandit650n
          MYSQL_DATABASE: formacion
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=bandit650n"
          --health-interval=10s --health-timeout=5s --health-retries=20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          ini-values: date.timezone=UTC
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env.test
        run: echo "DATABASE_URL_TEST=mysql://root:bandit650n@127.0.0.1:3306/formacion?serverVersion=8.0.32&charset=utf8mb4" > .env.test

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 -u root --password=bandit650n; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Debug MySQL Connection
        run: |
          echo "Testing MySQL connection"
          mysql -h 127.0.0.1 -u root --password=bandit650n -e "SHOW DATABASES;"

      - name: Run database migrations
        env:
          APP_ENV: test
          DATABASE_URL_TEST: mysql://root:bandit650n@127.0.0.1:3306/formacion?serverVersion=8.0.32&charset=utf8mb4
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Run PHPUnit tests
        env:
          APP_ENV: test
          DATABASE_URL_TEST: mysql://root:bandit650n@127.0.0.1:3306/formacion?serverVersion=8.0.32&charset=utf8mb4
        run: php bin/phpunit --coverage-text
