name: Run Symfony PHPUnit Tests

on:
  push:
    branches:
      - main
      - developer
  pull_request:
    branches:
      - main
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Crear archivo .env
      run: |
        echo "APP_ENV=test" > .env
        echo "DATABASE_URL=mysql://root:bandit650n@127.0.0.1:3306/formacion?serverVersion=8.0.32&charset=utf8mb4" >> .env
        echo "APP_SECRET=$ecretf0rt3st" >> .env

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Ajusta según la versión de PHP que utilices
        extensions: mbstring, intl, pdo_mysql
        ini-values: post_max_size=256M, max_execution_time=300
        coverage: none

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Run Symfony tests
      run: ./bin/phpunit

